// <auto-generated />
namespace AppraisalSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class int2string : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(int2string));
        
        string IMigrationMetadata.Id
        {
            get { return "202012210857352_int2string"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
