// <auto-generated />
namespace AppraisalSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class string2intTarget : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(string2intTarget));
        
        string IMigrationMetadata.Id
        {
            get { return "202012061338555_string2intTarget"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
