// <auto-generated />
namespace AppraisalSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class requiredfields3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(requiredfields3));
        
        string IMigrationMetadata.Id
        {
            get { return "202012211356370_requiredfields3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
