// <auto-generated />
namespace AppraisalSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class bool2stringProject : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(bool2stringProject));
        
        string IMigrationMetadata.Id
        {
            get { return "202012061332025_bool2stringProject"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
