// <auto-generated />
namespace AppraisalSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class PerformanceTargetNullable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PerformanceTargetNullable));
        
        string IMigrationMetadata.Id
        {
            get { return "202012201246272_PerformanceTargetNullable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
